// Telemetry gap audit for iRacing visual coverage.
//
// Parse-only Node ESM script: reads TypeScript sources as text, extracts normalized
// TelemetrySnapshot fields, widget `requires` coverage, and iRacing raw vars with or
// without `telemetryField` mappings. Writes concepts/knowledge/iracing-sdk/gap-report.md.
//
//   node visual-audit/telemetry-gap.mjs
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, extname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const APP = resolve(__dirname, '..')
const TELEMETRY = resolve(APP, 'src', 'shared', 'telemetry.ts')
const IRACING_VARS = resolve(APP, 'src', 'shared', 'iracing-vars.ts')
const WIDGETS = resolve(APP, 'src', 'renderer', 'src', 'hifi', 'widgets')
const REPORT_DIR = resolve(APP, 'concepts', 'knowledge', 'iracing-sdk')
const REPORT = resolve(REPORT_DIR, 'gap-report.md')

const NON_WIDGETABLE = new Set(['sim', 'connected', 'timestamp', 'playerCarIdx', 'drivers', 'relatives', 'radarCars'])

function log(...a) {
  console.log('[telemetry-gap]', ...a)
}

function readText(file) {
  if (!existsSync(file)) throw new Error(`Missing input: ${file}`)
  return readFileSync(file, 'utf8')
}

function unique(items) {
  return [...new Set(items)]
}

function listSourceFiles(dir) {
  const out = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name)
    if (entry.isDirectory()) out.push(...listSourceFiles(full))
    else if (entry.isFile() && ['.ts', '.tsx'].includes(extname(entry.name))) out.push(full)
  }
  return out.sort((a, b) => a.localeCompare(b))
}

function extractSnapshotFields(source) {
  const marker = 'export interface TelemetrySnapshot {'
  const start = source.indexOf(marker)
  if (start < 0) throw new Error('TelemetrySnapshot interface not found')
  const bodyStart = start + marker.length
  const end = source.indexOf('\n}', bodyStart)
  if (end < 0) throw new Error('TelemetrySnapshot interface closing brace not found')
  const body = source.slice(bodyStart, end)
  return unique([...body.matchAll(/^\s{2}([a-zA-Z][a-zA-Z0-9]*)\??:/gm)].map((m) => m[1]))
}

function extractIracingVars(source) {
  const start = source.indexOf('export const IRACING_VARIABLES')
  if (start < 0) throw new Error('IRACING_VARIABLES array not found')
  const end = source.indexOf('\n]', start)
  if (end < 0) throw new Error('IRACING_VARIABLES closing bracket not found')
  const body = source.slice(start, end + 2)
  const vars = []
  for (const match of body.matchAll(/{[^{}]*id:\s*'([^']+)'[^{}]*}/g)) {
    const objectText = match[0]
    vars.push({
      id: match[1],
      category: objectText.match(/category:\s*'([^']+)'/)?.[1] ?? 'unknown',
      hasTelemetryField: /telemetryField\s*:/.test(objectText)
    })
  }
  return vars
}

function extractWidgetCoverage(files) {
  const requiredFields = []
  let moduleCount = 0

  for (const file of files) {
    const source = readText(file)
    const display = relative(APP, file)
    moduleCount += [...source.matchAll(/^\s*id:\s*'([^']+)'/gm)].length

    for (const requiresMatch of source.matchAll(/requires:\s*\[([^\]]*)\]/g)) {
      for (const fieldMatch of requiresMatch[1].matchAll(/'([^']+)'/g)) {
        requiredFields.push({ field: fieldMatch[1], file: display })
      }
    }
  }

  return {
    moduleCount,
    requiredFields,
    requiredFieldSet: new Set(requiredFields.map((item) => item.field))
  }
}

function bulletList(items) {
  return items.length ? items.map((item) => `- ${item}`).join('\n') : '- None'
}

function buildReport({ snapshot, rawVars, widgets, covered, uncoveredVisual, nonWidgetableFields, rawWithoutField, rawByCategory }) {
  const lines = []
  lines.push('# iRacing telemetry gap report')
  lines.push('')
  lines.push('Generated by visual-audit/telemetry-gap.mjs')
  lines.push('')
  lines.push(`Generated at: ${new Date().toISOString()}`)
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(`- Snapshot fields: ${snapshot.length}`)
  lines.push(`- Snapshot fields covered by widget requires: ${covered.length}`)
  lines.push(`- Uncovered snapshot fields needing a widget: ${uncoveredVisual.length}`)
  lines.push(`- Non-widgetable snapshot fields tracked separately: ${nonWidgetableFields.length}`)
  lines.push(`- Widget modules counted: ${widgets.moduleCount}`)
  lines.push(`- Unique widget requires fields: ${widgets.requiredFieldSet.size}`)
  lines.push(`- Raw iRacing vars: ${rawVars.length}`)
  lines.push(`- Raw iRacing vars with telemetryField: ${rawVars.filter((v) => v.hasTelemetryField).length}`)
  lines.push(`- Raw iRacing vars without telemetryField: ${rawWithoutField.length}`)
  lines.push('')
  lines.push('## Raw var coverage by category')
  lines.push('')
  lines.push('| Category | Total | With telemetryField | Without telemetryField |')
  lines.push('| --- | ---: | ---: | ---: |')
  for (const [category, counts] of rawByCategory) {
    lines.push(`| ${category} | ${counts.total} | ${counts.withField} | ${counts.withoutField} |`)
  }
  lines.push('')
  lines.push('## Covered snapshot fields (in widget requires)')
  lines.push('')
  lines.push(bulletList(covered))
  lines.push('')
  lines.push('## Uncovered snapshot fields (need a widget)')
  lines.push('')
  lines.push(bulletList(uncoveredVisual))
  lines.push('')
  lines.push('## Non-widgetable snapshot fields (tracked separately)')
  lines.push('')
  lines.push(bulletList(nonWidgetableFields.map((field) => `${field}${widgets.requiredFieldSet.has(field) ? ' (covered)' : ' (not widget-required)'}`)))
  lines.push('')
  lines.push('## Unsurfaced raw vars (no telemetryField)')
  lines.push('')
  lines.push(bulletList(rawWithoutField.map((v) => v.id)))
  lines.push('')
  return `${lines.join('\n')}\n`
}

function main() {
  const snapshot = extractSnapshotFields(readText(TELEMETRY))
  const rawVars = extractIracingVars(readText(IRACING_VARS))
  const widgetFiles = listSourceFiles(WIDGETS)
  const widgets = extractWidgetCoverage(widgetFiles)

  const covered = snapshot.filter((field) => widgets.requiredFieldSet.has(field))
  const uncovered = snapshot.filter((field) => !widgets.requiredFieldSet.has(field))
  const nonWidgetableFields = snapshot.filter((field) => NON_WIDGETABLE.has(field))
  const uncoveredVisual = uncovered.filter((field) => !NON_WIDGETABLE.has(field))
  const rawWithoutField = rawVars.filter((variable) => !variable.hasTelemetryField)

  const rawByCategoryMap = new Map()
  for (const variable of rawVars) {
    const counts = rawByCategoryMap.get(variable.category) ?? { total: 0, withField: 0, withoutField: 0 }
    counts.total += 1
    if (variable.hasTelemetryField) counts.withField += 1
    else counts.withoutField += 1
    rawByCategoryMap.set(variable.category, counts)
  }
  const rawByCategory = [...rawByCategoryMap.entries()].sort((a, b) => a[0].localeCompare(b[0]))

  mkdirSync(REPORT_DIR, { recursive: true })
  writeFileSync(REPORT, buildReport({ snapshot, rawVars, widgets, covered, uncoveredVisual, nonWidgetableFields, rawWithoutField, rawByCategory }), 'utf8')

  console.log('\n──────── telemetry-gap summary ────────')
  console.log(`  snapshot fields       : ${snapshot.length}`)
  console.log(`  covered by widgets    : ${covered.length}`)
  console.log(`  uncovered need widget : ${uncoveredVisual.length}`)
  console.log(`  non-widgetable noted  : ${nonWidgetableFields.length}`)
  console.log(`  widget modules        : ${widgets.moduleCount}`)
  console.log(`  unique requires fields: ${widgets.requiredFieldSet.size}`)
  console.log(`  raw vars              : ${rawVars.length}`)
  console.log(`  raw with field        : ${rawVars.length - rawWithoutField.length}`)
  console.log(`  raw without field     : ${rawWithoutField.length}`)
  console.log(`\n  report → ${REPORT}`)
  console.log('────────────────────────────────────────\n')

  log('uncovered snapshot fields:', uncoveredVisual.length ? uncoveredVisual.join(', ') : 'none')
  log('unsurfaced raw vars:', rawWithoutField.length ? rawWithoutField.map((v) => v.id).join(', ') : 'none')
}

main()