import type { HifiWidgetModule } from '../types'
import { unitTagFor } from '../../../../../shared/tags'
import {
  createCompetitionRenderer,
  createDduRenderer,
  createFuturisticRenderer,
  defaultSizeFor
} from './factories'
import { createComplexRenderer, complexDefaultSizeFor } from './complex-factories'
import { COMPLEX_TELEMETRY_DESCRIPTORS } from './complex-descriptors'
import { SNAPSHOT_GAP_DESCRIPTORS } from './snapshot-gap-descriptors'
import { TELEMETRY_VARIANTS, type TelemetryArchetype, type TelemetryDescriptor, type TelemetryVariant } from './types'
import type { ComplexTelemetryArchetype, ComplexTelemetryDescriptor } from './complex-types'
import { telemetryVariantModuleId } from './widgets'

const VARIANT_LABELS: Record<TelemetryVariant, string> = {
  competition: 'Competition',
  futuristic: 'Futuristic',
  ddu: 'DDU-inspired'
}

const CORE_ARCHETYPE_TAGS: Record<TelemetryArchetype, string[]> = {
  radial: ['gauge', 'radial'],
  linear: ['bar', 'linear'],
  digital: ['digital', 'bignum'],
  indicator: ['status', 'indicator']
}

const COMPLEX_ARCHETYPE_TAGS: Record<ComplexTelemetryArchetype, string[]> = {
  table: ['table', 'standings'],
  radar: ['radar', 'relative'],
  map: ['map', 'track-map'],
  vector: ['graph', 'vector'],
  corners: ['heatmap', 'corner-grid'],
  status: ['status', 'indicator'],
  steering: ['gauge', 'steering']
}

function unique(tags: readonly string[]): string[] {
  return [...new Set(tags.filter(Boolean))]
}

function scalarRenderer(
  descriptor: TelemetryDescriptor,
  variant: TelemetryVariant
): HifiWidgetModule['render'] {
  if (variant === 'competition') return createCompetitionRenderer(descriptor)
  if (variant === 'futuristic') return createFuturisticRenderer(descriptor)
  return createDduRenderer(descriptor)
}

function commonTags(
  descriptor: Pick<TelemetryDescriptor, 'id' | 'category' | 'focus' | 'tags'>,
  variant: TelemetryVariant,
  archetypeTags: readonly string[],
  unit?: string
): string[] {
  return unique([
    'telemetry-framework',
    'iRacing',
    'source-iracing',
    'widget',
    'telemetry',
    `telemetry-${descriptor.id}`,
    descriptor.category,
    descriptor.focus,
    `focus-${descriptor.focus}`,
    variant,
    `style-${variant}`,
    ...(variant === 'ddu' ? ['ddu-inspired'] : []),
    ...archetypeTags,
    unitTagFor(unit) ?? '',
    ...(descriptor.tags ?? [])
  ])
}

export const SNAPSHOT_GAP_WIDGETS: HifiWidgetModule[] = SNAPSHOT_GAP_DESCRIPTORS.flatMap(
  (descriptor) =>
    TELEMETRY_VARIANTS.map((variant) => ({
      id: telemetryVariantModuleId(descriptor.id, variant),
      title: `${descriptor.label} — ${VARIANT_LABELS[variant]}`,
      description: `${descriptor.label} ${VARIANT_LABELS[variant].toLowerCase()} telemetry instrument generated by the shared ${descriptor.archetype} factory.`,
      category: descriptor.category,
      tags: commonTags(
        descriptor,
        variant,
        CORE_ARCHETYPE_TAGS[descriptor.archetype],
        descriptor.unit
      ),
      requires: [...descriptor.requires],
      defaultSize: defaultSizeFor(descriptor, variant),
      render: scalarRenderer(descriptor, variant)
    }))
)

function complexWidget(
  descriptor: ComplexTelemetryDescriptor,
  variant: TelemetryVariant
): HifiWidgetModule {
  return {
    id: telemetryVariantModuleId(descriptor.id, variant),
    title: `${descriptor.label} — ${VARIANT_LABELS[variant]}`,
    description: `${descriptor.label} ${VARIANT_LABELS[variant].toLowerCase()} telemetry instrument generated by the shared ${descriptor.archetype} archetype.`,
    category: descriptor.category,
    tags: commonTags(
      descriptor,
      variant,
      COMPLEX_ARCHETYPE_TAGS[descriptor.archetype]
    ),
    requires: [...descriptor.requires],
    defaultSize: complexDefaultSizeFor(descriptor, variant),
    render: createComplexRenderer(descriptor, variant)
  }
}

export const COMPLEX_ARCHETYPE_WIDGETS: HifiWidgetModule[] =
  COMPLEX_TELEMETRY_DESCRIPTORS.flatMap((descriptor) =>
    TELEMETRY_VARIANTS.map((variant) => complexWidget(descriptor, variant))
  )

/** Snapshot-gap scalars plus table/radar/map/vector/corner/status archetypes. */
export const REMAINING_TELEMETRY_WIDGETS: HifiWidgetModule[] = [
  ...SNAPSHOT_GAP_WIDGETS,
  ...COMPLEX_ARCHETYPE_WIDGETS
]
