import type { HifiWidgetModule } from '../types'
import { unitTagFor } from '../../../../../shared/tags'
import {
  RELEASE_A_CATALOG_ORDER,
  RELEASE_A_RELEASED_AT,
  RELEASE_A_TAG
} from '../../../../../shared/catalog-order'
import { overlayTriggerTags } from '../../../../../shared/overlays'
import {
  createCompetitionRenderer,
  createDduRenderer,
  createFuturisticRenderer,
  defaultSizeFor
} from './factories'
import { TELEMETRY_DESCRIPTORS } from './descriptors'
import {
  TELEMETRY_VARIANTS,
  type TelemetryArchetype,
  type TelemetryDescriptor,
  type TelemetryVariant
} from './types'

const VARIANT_LABELS: Record<TelemetryVariant, string> = {
  competition: 'Competition',
  futuristic: 'Futuristic',
  ddu: 'DDU-inspired'
}

const ARCHETYPE_TAGS: Record<TelemetryArchetype, string[]> = {
  radial: ['gauge', 'radial'],
  linear: ['bar', 'linear'],
  digital: ['digital', 'bignum'],
  indicator: ['status', 'led']
}

function unique(tags: readonly string[]): string[] {
  return [...new Set(tags.filter(Boolean))]
}

function rendererFor(
  descriptor: TelemetryDescriptor,
  variant: TelemetryVariant
): HifiWidgetModule['render'] {
  if (variant === 'competition') return createCompetitionRenderer(descriptor)
  if (variant === 'futuristic') return createFuturisticRenderer(descriptor)
  return createDduRenderer(descriptor)
}

/** Stable hi-fi module id for artifact `w:<telemetryKey>:<variant>`. */
export function telemetryVariantModuleId(
  telemetryKey: string,
  variant: TelemetryVariant
): string {
  return `telemetry-${telemetryKey}-${variant}`
}

/** Runtime/catalog widget id resolved by resolveWidgetComponent. */
export function telemetryVariantWidgetId(
  telemetryKey: string,
  variant: TelemetryVariant
): `hifi:${string}` {
  return `hifi:${telemetryVariantModuleId(telemetryKey, variant)}`
}

/** Session artifact row id used by the 429-row implementation tracker. */
export function telemetryVariantArtifactId(
  telemetryKey: string,
  variant: TelemetryVariant
): string {
  return `w:${telemetryKey}:${variant}`
}

/** One descriptor table × three pure-SVG factories = every implemented variant. */
export const TELEMETRY_VARIANT_WIDGETS: HifiWidgetModule[] =
  TELEMETRY_DESCRIPTORS.flatMap((descriptor) =>
    TELEMETRY_VARIANTS.map((variant) => ({
      id: telemetryVariantModuleId(descriptor.id, variant),
      title: `${descriptor.label} — ${VARIANT_LABELS[variant]}`,
      description: `${descriptor.label} ${VARIANT_LABELS[variant].toLowerCase()} telemetry instrument generated by the shared ${descriptor.archetype} factory.`,
      category: descriptor.category,
      tags: unique([
        'telemetry-framework',
        'iRacing',
        'source-iracing',
        'widget',
        'telemetry',
        `telemetry-${descriptor.id}`,
        descriptor.category,
        descriptor.focus,
        `focus-${descriptor.focus}`,
        variant,
        `style-${variant}`,
        ...(variant === 'ddu' ? ['ddu-inspired'] : []),
        ...ARCHETYPE_TAGS[descriptor.archetype],
        unitTagFor(descriptor.unit) ?? '',
        ...(descriptor.tags ?? []),
        ...overlayTriggerTags(descriptor.visibility?.trigger),
        ...(descriptor.visibility ? [RELEASE_A_TAG] : [])
      ]),
      requires: [...descriptor.requires],
      defaultSize: defaultSizeFor(descriptor, variant),
      role: descriptor.visibility?.role,
      defaultTrigger: descriptor.visibility?.trigger,
      preview: descriptor.visibility?.preview,
      catalogOrder: descriptor.visibility ? RELEASE_A_CATALOG_ORDER : undefined,
      releasedAt: descriptor.visibility ? RELEASE_A_RELEASED_AT : undefined,
      render: rendererFor(descriptor, variant)
    }))
  )
