export const VISUAL_ARTIFACT_LEDGER_VERSION = 2 as const
export const GOVERNED_STYLE_COUNT = 50 as const
export const GOVERNED_CONCEPT_COUNT = 143 as const
export const BASE_ARTIFACT_COUNT = 14_350 as const
export const MIN_TRIGGER_ARTIFACT_COUNT = 500 as const
export const MIN_TOTAL_ARTIFACT_COUNT = 14_850 as const
export const IMAGE_REQUEST_LIMIT = 6 as const

export const MAX_ARTIFACTS = 15_000 as const
export const MAX_REVISIONS_PER_ARTIFACT = 2 as const
export const MAX_IMAGE_ATTEMPTS = 3 as const
export const MAX_EVENTS_PER_ACCEPTED_REVISION = 9 as const
export const MAX_EVIDENCE_PER_ACCEPTED_REVISION = 9 as const
export const MAX_SCHEDULER_EVENTS_PER_ATTEMPT = 3 as const
export const MAX_LEDGER_EVENTS =
  MAX_ARTIFACTS * MAX_REVISIONS_PER_ARTIFACT * MAX_EVENTS_PER_ACCEPTED_REVISION + 1
export const MAX_SCHEDULER_EVENTS =
  MAX_ARTIFACTS *
    MAX_REVISIONS_PER_ARTIFACT *
    MAX_IMAGE_ATTEMPTS *
    MAX_SCHEDULER_EVENTS_PER_ATTEMPT +
  1
export const MAX_EVIDENCE =
  MAX_ARTIFACTS * MAX_REVISIONS_PER_ARTIFACT * MAX_EVIDENCE_PER_ACCEPTED_REVISION
export const MAX_SERIALIZED_BYTES_PER_ARTIFACT_REVISION = 24_000 as const
export const MAX_SERIALIZED_BYTES_PER_SCHEDULER_ATTEMPT = 8_000 as const
export const MAX_SERIALIZED_PLAN_BYTES = 8 * 1024 * 1024
export const MAX_SERIALIZED_BYTES = 768 * 1024 * 1024
export const MAX_STRING_LENGTH = 512 as const
export const MAX_IDENTIFIER_LENGTH = 128 as const
export const MAX_CANONICAL_DEPTH = 32 as const
export const MAX_CANONICAL_NODES_PER_EVENT = 64 as const
export const MAX_CANONICAL_NODES =
  MAX_LEDGER_EVENTS * MAX_CANONICAL_NODES_PER_EVENT + 100_000

export const ZERO_HASH = '0'.repeat(64)
