import { constants as BUFFER_CONSTANTS } from 'node:buffer'

export const VISUAL_ARTIFACT_LEDGER_VERSION = 2 as const
export const GOVERNED_STYLE_COUNT = 50 as const
export const GOVERNED_CONCEPT_COUNT = 143 as const
export const BASE_ARTIFACT_COUNT = 14_350 as const
export const MIN_TRIGGER_ARTIFACT_COUNT = 500 as const
export const MIN_TOTAL_ARTIFACT_COUNT = 14_850 as const
export const APPROVED_EXACT_ARTIFACT_COUNT = 16_600 as const
export const IMAGE_REQUEST_LIMIT = 6 as const

export const MAX_PLAN_ARTIFACTS = 17_000 as const
export const MAX_ARTIFACTS = MAX_PLAN_ARTIFACTS
export const MAX_REVISIONS_PER_ARTIFACT = 2 as const
export const MAX_IMAGE_ATTEMPTS = 3 as const
export const MAX_SCHEDULER_LOGICAL_ATTEMPTS =
  MAX_ARTIFACTS * MAX_REVISIONS_PER_ARTIFACT * MAX_IMAGE_ATTEMPTS
export const MAX_EVENTS_PER_ACCEPTED_REVISION = 9 as const
export const MAX_EVIDENCE_PER_ACCEPTED_REVISION = 9 as const
export const MAX_SCHEDULER_EVENTS_PER_ATTEMPT = 3 as const
export const MAX_RESERVATION_RELEASES = 200 as const
export const MAX_SCHEDULER_EVENTS_PER_RELEASE = 2 as const
export const MAX_LEDGER_EVENTS =
  MAX_ARTIFACTS * MAX_REVISIONS_PER_ARTIFACT * MAX_EVENTS_PER_ACCEPTED_REVISION + 1
export const MAX_SCHEDULER_EVENTS =
  MAX_SCHEDULER_LOGICAL_ATTEMPTS * MAX_SCHEDULER_EVENTS_PER_ATTEMPT +
  MAX_RESERVATION_RELEASES * MAX_SCHEDULER_EVENTS_PER_RELEASE +
  1
export const MAX_EVIDENCE =
  MAX_ARTIFACTS * MAX_REVISIONS_PER_ARTIFACT * MAX_EVIDENCE_PER_ACCEPTED_REVISION
export const MAX_SERIALIZED_BYTES_PER_ARTIFACT_REVISION = 13_100 as const
export const MAX_SERIALIZED_BYTES_PER_SCHEDULER_ATTEMPT = 4_450 as const
export const MAX_SERIALIZED_PLAN_BYTES = 8 * 1024 * 1024
export const MAX_SERIALIZED_ENVELOPE_FRAMING_BYTES = 1024 * 1024
export const MAX_SERIALIZED_EVENT_SEPARATOR_BYTES = Math.max(
  MAX_LEDGER_EVENTS,
  MAX_SCHEDULER_EVENTS
)
export const MAX_SERIALIZED_JSON_FRAMING_BYTES =
  MAX_SERIALIZED_ENVELOPE_FRAMING_BYTES + MAX_SERIALIZED_EVENT_SEPARATOR_BYTES
export const MAX_SERIALIZED_LEDGER_FRAMING_BYTES =
  MAX_SERIALIZED_PLAN_BYTES + MAX_SERIALIZED_JSON_FRAMING_BYTES
export const MAX_SERIALIZED_SCHEDULER_FRAMING_BYTES =
  MAX_SERIALIZED_ENVELOPE_FRAMING_BYTES + MAX_SERIALIZED_EVENT_SEPARATOR_BYTES
export const RUNTIME_MAX_STRING_LENGTH = BUFFER_CONSTANTS.MAX_STRING_LENGTH
export const SERIALIZED_STRING_SAFETY_PERCENT = 85 as const
export const MAX_SERIALIZED_CHARACTERS = Math.floor(
  (RUNTIME_MAX_STRING_LENGTH * SERIALIZED_STRING_SAFETY_PERCENT) / 100
)
export const MAX_SERIALIZED_BYTES = MAX_SERIALIZED_CHARACTERS
export const MAX_STRING_LENGTH = 512 as const
export const MAX_IDENTIFIER_LENGTH = 80 as const
export const MAX_PLAN_ID_LENGTH = 24 as const
export const MAX_CANONICAL_DEPTH = 32 as const
export const MAX_CANONICAL_NODES_PER_EVENT = 64 as const
export const MAX_CANONICAL_NODES =
  Math.max(MAX_LEDGER_EVENTS, MAX_SCHEDULER_EVENTS) *
    MAX_CANONICAL_NODES_PER_EVENT +
  100_000

export const ZERO_HASH = '0'.repeat(64)
