export const PASSPORT_APP_PERSISTENCE_DEADLINE_MS = 2_500
export const PASSPORT_SERVICE_DRAIN_DEADLINE_MS = 600
export const PASSPORT_CLIENT_CLOSE_DEADLINE_MS = 900
export const PASSPORT_WORKER_TERMINATION_DEADLINE_MS = 300
export const PASSPORT_SQLITE_BUSY_TIMEOUT_MS = 200

export const PASSPORT_PERSISTENCE_WORST_CASE_MS =
  PASSPORT_SERVICE_DRAIN_DEADLINE_MS +
  PASSPORT_CLIENT_CLOSE_DEADLINE_MS +
  PASSPORT_WORKER_TERMINATION_DEADLINE_MS +
  PASSPORT_SQLITE_BUSY_TIMEOUT_MS
