import { createButtonBoxPanel, type ButtonBoxPanel } from './touch-panel'

export const TOUCH_PRESETS_A: ButtonBoxPanel[] = [
  createButtonBoxPanel({
    id: 'tp-a-pit-stop-control',
    name: 'Pit Stop — Controle',
    columns: 4,
    rows: 4,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'Pit Req', material: 'guarded', icon: 'pit-sign', bodyColor: '#b45309', borderColor: '#f59e0b', textColor: '#fff7ed', action: { kind: 'keyboard', command: { mode: 'press', keys: ['P'] } } },
      { label: 'Fuel +5', material: 'backlit', icon: 'fuel', bodyColor: '#0f3b57', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 5 } } },
      { label: 'Fuel +10', material: 'backlit', icon: 'fuel', bodyColor: '#0f3b57', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 10 } } },
      { label: 'Fuel +25', material: 'backlit', icon: 'fuel', bodyColor: '#0f3b57', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 25 } } },
      { label: 'Fuel CLR', material: 'guarded', icon: 'fuel-alarm', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearFuel' } } },
      { label: 'Tear Off', material: 'backlit', icon: 'tear-off', bodyColor: '#1e3a8a', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['T'] } } },
      { label: 'Repair', material: 'guarded', icon: 'fast-repair', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:fastRepair' } } },
      { label: 'Limiter', material: 'toggle', icon: 'limiter', bodyColor: '#92400e', borderColor: '#facc15', textColor: '#fef3c7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['L'] } } },
      { label: 'Tyre LF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLf' } } },
      { label: 'Tyre RF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRf' } } },
      { label: 'Tyre LR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLr' } } },
      { label: 'Tyre RR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRr' } } },
      { label: 'Clear All', material: 'guarded', icon: 'reset', bodyColor: '#991b1b', borderColor: '#ef4444', textColor: '#fee2e2', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearAll' } } },
      { label: 'BB Next', material: 'glass', icon: 'dash-next', bodyColor: '#1e293b', borderColor: '#94a3b8', textColor: '#f8fafc', action: { kind: 'iracing', command: { group: 'blackBox', name: 'blackBox:next' } } },
      { label: 'BB Prev', material: 'glass', icon: 'dash-prev', bodyColor: '#1e293b', borderColor: '#94a3b8', textColor: '#f8fafc', action: { kind: 'iracing', command: { group: 'blackBox', name: 'blackBox:previous' } } },
      { label: 'Mark', material: 'backlit', icon: 'mark', bodyColor: '#312e81', borderColor: '#818cf8', textColor: '#eef2ff', action: { kind: 'keyboard', command: { mode: 'press', keys: ['M'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-pit-stop-sprint',
    name: 'Pit Stop — Sprint',
    columns: 4,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'Pit Req', material: 'guarded', icon: 'pit-sign', bodyColor: '#b45309', borderColor: '#f59e0b', textColor: '#fff7ed', action: { kind: 'keyboard', command: { mode: 'press', keys: ['P'] } } },
      { label: '+10L', material: 'backlit', icon: 'fuel', bodyColor: '#0f3b57', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 10 } } },
      { label: '+25L', material: 'backlit', icon: 'fuel', bodyColor: '#0f3b57', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 25 } } },
      { label: 'Fuel CLR', material: 'guarded', icon: 'fuel-alarm', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearFuel' } } },
      { label: 'LF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLf' } } },
      { label: 'RF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRf' } } },
      { label: 'LR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLr' } } },
      { label: 'RR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRr' } } },
      { label: 'Limiter', material: 'toggle', icon: 'limiter', bodyColor: '#92400e', borderColor: '#facc15', textColor: '#fef3c7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['L'] } } },
      { label: 'Repair', material: 'guarded', icon: 'fast-repair', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:fastRepair' } } },
      { label: 'Tear Off', material: 'backlit', icon: 'tear-off', bodyColor: '#1e3a8a', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['T'] } } },
      { label: 'Clear All', material: 'guarded', icon: 'reset', bodyColor: '#991b1b', borderColor: '#ef4444', textColor: '#fee2e2', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearAll' } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-fuel-management',
    name: 'Fuel',
    columns: 5,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: '+1L', material: 'backlit', icon: 'fuel', bodyColor: '#78350f', borderColor: '#f59e0b', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 1 } } },
      { label: '+5L', material: 'backlit', icon: 'fuel', bodyColor: '#78350f', borderColor: '#f59e0b', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 5 } } },
      { label: '+10L', material: 'backlit', icon: 'fuel', bodyColor: '#78350f', borderColor: '#f59e0b', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 10 } } },
      { label: '+25L', material: 'backlit', icon: 'fuel', bodyColor: '#92400e', borderColor: '#fbbf24', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 25 } } },
      { label: '+50L', material: 'backlit', icon: 'fuel', bodyColor: '#92400e', borderColor: '#fbbf24', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 50 } } },
      { label: 'Fuel CLR', material: 'guarded', icon: 'fuel-alarm', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearFuel' } } },
      { label: 'Alarm', material: 'led_status', icon: 'fuel-alarm', bodyColor: '#991b1b', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'toggle', keys: ['F9'] } } },
      { label: 'Add Full', material: 'guarded', icon: 'fuel', bodyColor: '#854d0e', borderColor: '#facc15', textColor: '#fef9c3', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 999 } } },
      { label: 'BB Next', material: 'glass', icon: 'dash-next', bodyColor: '#1f2937', borderColor: '#f59e0b', textColor: '#fef3c7', action: { kind: 'iracing', command: { group: 'blackBox', name: 'blackBox:next' } } },
      { label: 'BB Prev', material: 'glass', icon: 'dash-prev', bodyColor: '#1f2937', borderColor: '#f59e0b', textColor: '#fef3c7', action: { kind: 'iracing', command: { group: 'blackBox', name: 'blackBox:previous' } } },
      { label: 'Map', material: 'backlit', icon: 'map', bodyColor: '#4338ca', borderColor: '#a5b4fc', textColor: '#eef2ff', action: { kind: 'app', command: { name: 'overlays:toggle', overlayId: 'fuel-map' } } },
      { label: 'Delta', material: 'backlit', icon: 'delta', bodyColor: '#0f766e', borderColor: '#5eead4', textColor: '#ccfbf1', action: { kind: 'app', command: { name: 'overlays:toggle', overlayId: 'fuel-delta' } } },
      { label: 'Dash', material: 'backlit', icon: 'dash', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'app', command: { name: 'oled:setActivePage', pageIndex: 1 } } },
      { label: 'Lap Calc', material: 'backlit', icon: 'settings', bodyColor: '#365314', borderColor: '#84cc16', textColor: '#ecfccb', action: { kind: 'keyboard', command: { mode: 'press', keys: ['F10'] } } },
      { label: 'Mark', material: 'backlit', icon: 'mark', bodyColor: '#312e81', borderColor: '#818cf8', textColor: '#eef2ff', action: { kind: 'keyboard', command: { mode: 'press', keys: ['M'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-fuel-management-eco',
    name: 'Fuel — Eco',
    columns: 4,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: '+1L', material: 'backlit', icon: 'fuel', bodyColor: '#78350f', borderColor: '#f59e0b', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 1 } } },
      { label: '+5L', material: 'backlit', icon: 'fuel', bodyColor: '#78350f', borderColor: '#f59e0b', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 5 } } },
      { label: '+10L', material: 'backlit', icon: 'fuel', bodyColor: '#92400e', borderColor: '#fbbf24', textColor: '#fffbeb', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 10 } } },
      { label: 'Clear', material: 'guarded', icon: 'fuel-alarm', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearFuel' } } },
      { label: 'Alarm', material: 'led_status', icon: 'fuel-alarm', bodyColor: '#991b1b', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'toggle', keys: ['F9'] } } },
      { label: 'Save', material: 'toggle', icon: 'fuel', bodyColor: '#14532d', borderColor: '#4ade80', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['6'] } } },
      { label: 'Push', material: 'toggle', icon: 'fuel', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['7'] } } },
      { label: 'Full', material: 'guarded', icon: 'fuel', bodyColor: '#854d0e', borderColor: '#facc15', textColor: '#fef9c3', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:addFuel', fuelLiters: 999 } } },
      { label: 'Dash +', material: 'backlit', icon: 'dash-next', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'app', command: { name: 'dash:cycleNext' } } },
      { label: 'Dash -', material: 'backlit', icon: 'dash-prev', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'app', command: { name: 'dash:cyclePrev' } } },
      { label: 'Overlay', material: 'glass', icon: 'overlay', bodyColor: '#4338ca', borderColor: '#a5b4fc', textColor: '#eef2ff', action: { kind: 'app', command: { name: 'overlays:toggle', overlayId: 'fuel' } } },
      { label: 'Mark', material: 'backlit', icon: 'mark', bodyColor: '#312e81', borderColor: '#818cf8', textColor: '#eef2ff', action: { kind: 'keyboard', command: { mode: 'press', keys: ['M'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-tyre-strategy',
    name: 'Estratégia de Tires',
    columns: 4,
    rows: 4,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'LF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLf' } } },
      { label: 'RF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRf' } } },
      { label: 'LR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLr' } } },
      { label: 'RR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRr' } } },
      { label: 'All Tyres', material: 'toggle', icon: 'tyre', bodyColor: '#0369a1', borderColor: '#7dd3fc', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['Alt', 'T', 'A'] } } },
      { label: 'No Tyres', material: 'guarded', icon: 'tyre', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['Alt', 'T', 'N'] } } },
      { label: 'Cold', material: 'led_status', icon: 'cold', bodyColor: '#1e3a8a', borderColor: '#93c5fd', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['F5'] } } },
      { label: 'Wet', material: 'led_status', icon: 'wet', bodyColor: '#075985', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['F6'] } } },
      { label: 'PSI LF+', material: 'backlit', icon: 'tyre', bodyColor: '#0e7490', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['L', 'F', '+'] } } },
      { label: 'PSI LF-', material: 'backlit', icon: 'tyre', bodyColor: '#0e7490', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['L', 'F', '-'] } } },
      { label: 'PSI RF+', material: 'backlit', icon: 'tyre', bodyColor: '#0e7490', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['R', 'F', '+'] } } },
      { label: 'PSI RF-', material: 'backlit', icon: 'tyre', bodyColor: '#0e7490', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['R', 'F', '-'] } } },
      { label: 'Tear Off', material: 'backlit', icon: 'tear-off', bodyColor: '#1e3a8a', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['T'] } } },
      { label: 'Pit Req', material: 'guarded', icon: 'pit-sign', bodyColor: '#b45309', borderColor: '#f59e0b', textColor: '#fff7ed', action: { kind: 'keyboard', command: { mode: 'press', keys: ['P'] } } },
      { label: 'Clear All', material: 'guarded', icon: 'reset', bodyColor: '#991b1b', borderColor: '#ef4444', textColor: '#fee2e2', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:clearAll' } } },
      { label: 'BB Tyres', material: 'glass', icon: 'dash', bodyColor: '#1f2937', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'blackBox', name: 'blackBox:next' } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-tyre-strategy-wet',
    name: 'Tires — Chuva',
    columns: 4,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'Wet Set', material: 'toggle', icon: 'wet', bodyColor: '#075985', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['F6'] } } },
      { label: 'Rain', material: 'led_status', icon: 'rain', bodyColor: '#1e3a8a', borderColor: '#93c5fd', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'toggle', keys: ['R'] } } },
      { label: 'Wiper', material: 'toggle', icon: 'wiper', bodyColor: '#0f766e', borderColor: '#5eead4', textColor: '#ccfbf1', action: { kind: 'keyboard', command: { mode: 'press', keys: ['W'] } } },
      { label: 'Light', material: 'toggle', icon: 'headlight', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['H'] } } },
      { label: 'LF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLf' } } },
      { label: 'RF', material: 'backlit', icon: 'tyre', bodyColor: '#155e75', borderColor: '#22d3ee', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRf' } } },
      { label: 'LR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreLr' } } },
      { label: 'RR', material: 'backlit', icon: 'tyre', bodyColor: '#164e63', borderColor: '#67e8f9', textColor: '#ecfeff', action: { kind: 'iracing', command: { group: 'pit', name: 'pit:toggleTyreRr' } } },
      { label: 'All Wet', material: 'toggle', icon: 'tyre', bodyColor: '#0369a1', borderColor: '#7dd3fc', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['Alt', 'W', 'A'] } } },
      { label: 'No Tyres', material: 'guarded', icon: 'tyre', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['Alt', 'T', 'N'] } } },
      { label: 'Cold PSI', material: 'backlit', icon: 'cold', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'keyboard', command: { mode: 'sequence', keys: ['C', 'O', 'L', 'D'] } } },
      { label: 'Pit Req', material: 'guarded', icon: 'pit-sign', bodyColor: '#b45309', borderColor: '#f59e0b', textColor: '#fff7ed', action: { kind: 'keyboard', command: { mode: 'press', keys: ['P'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-brake-tc-abs-trims',
    name: 'Brake / TC / ABS',
    columns: 4,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'BB +', material: 'rotary', icon: 'brake-bias', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: [']'] } } },
      { label: 'BB -', material: 'rotary', icon: 'brake-bias', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: ['['] } } },
      { label: 'TC +', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['='] } } },
      { label: 'TC -', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['-'] } } },
      { label: 'TC2 +', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fdba74', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Shift', '='] } } },
      { label: 'TC2 -', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fdba74', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Shift', '-'] } } },
      { label: 'ABS +', material: 'rotary', icon: 'brake-bias', bodyColor: '#991b1b', borderColor: '#fb7185', textColor: '#ffe4e6', action: { kind: 'keyboard', command: { mode: 'press', keys: ['.'] } } },
      { label: 'ABS -', material: 'rotary', icon: 'brake-bias', bodyColor: '#991b1b', borderColor: '#fb7185', textColor: '#ffe4e6', action: { kind: 'keyboard', command: { mode: 'press', keys: [','] } } },
      { label: 'Diff En', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['1'] } } },
      { label: 'Diff Mid', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['2'] } } },
      { label: 'Diff Ex', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['3'] } } },
      { label: 'Reset', material: 'guarded', icon: 'reset', bodyColor: '#450a0a', borderColor: '#ef4444', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: ['0'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-brake-tc-abs-gt3',
    name: 'Brake / TC / ABS — GT3',
    columns: 5,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'BB +', material: 'rotary', icon: 'brake-bias', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: [']'] } } },
      { label: 'BB -', material: 'rotary', icon: 'brake-bias', bodyColor: '#7f1d1d', borderColor: '#f87171', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: ['['] } } },
      { label: 'TC +', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['='] } } },
      { label: 'TC -', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['-'] } } },
      { label: 'Map +', material: 'rotary', icon: 'settings', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['8'] } } },
      { label: 'ABS +', material: 'rotary', icon: 'brake-bias', bodyColor: '#991b1b', borderColor: '#fb7185', textColor: '#ffe4e6', action: { kind: 'keyboard', command: { mode: 'press', keys: ['.'] } } },
      { label: 'ABS -', material: 'rotary', icon: 'brake-bias', bodyColor: '#991b1b', borderColor: '#fb7185', textColor: '#ffe4e6', action: { kind: 'keyboard', command: { mode: 'press', keys: [','] } } },
      { label: 'TC2 +', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fdba74', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Shift', '='] } } },
      { label: 'TC2 -', material: 'rotary', icon: 'brake-bias', bodyColor: '#9a3412', borderColor: '#fdba74', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Shift', '-'] } } },
      { label: 'Map -', material: 'rotary', icon: 'settings', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['7'] } } },
      { label: 'Diff En', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['1'] } } },
      { label: 'Diff Mid', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['2'] } } },
      { label: 'Diff Ex', material: 'backlit', icon: 'settings', bodyColor: '#7c2d12', borderColor: '#fb923c', textColor: '#ffedd5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['3'] } } },
      { label: 'Dash +', material: 'backlit', icon: 'dash-next', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'app', command: { name: 'dash:cycleNext' } } },
      { label: 'Reset', material: 'guarded', icon: 'reset', bodyColor: '#450a0a', borderColor: '#ef4444', textColor: '#fee2e2', action: { kind: 'keyboard', command: { mode: 'press', keys: ['0'] } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-endurance-radio-lights',
    name: 'Endurance — Rádio & Luzes',
    columns: 4,
    rows: 4,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'PTT', material: 'rotary', icon: 'radio', bodyColor: '#14532d', borderColor: '#4ade80', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'hold', keys: ['T'] } } },
      { label: 'Mic Mute', material: 'toggle', icon: 'mic-mute', bodyColor: '#365314', borderColor: '#84cc16', textColor: '#ecfccb', action: { kind: 'keyboard', command: { mode: 'toggle', keys: ['M'] } } },
      { label: 'Vol +', material: 'rotary', icon: 'volume-up', bodyColor: '#166534', borderColor: '#86efac', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['VolumeUp'] } } },
      { label: 'Vol -', material: 'rotary', icon: 'volume-down', bodyColor: '#166534', borderColor: '#86efac', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['VolumeDown'] } } },
      { label: 'Lights', material: 'toggle', icon: 'headlight', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['H'] } } },
      { label: 'High', material: 'toggle', icon: 'highbeam', bodyColor: '#854d0e', borderColor: '#facc15', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['K'] } } },
      { label: 'Flash', material: 'backlit', icon: 'highbeam', bodyColor: '#a16207', borderColor: '#fef08a', textColor: '#fefce8', action: { kind: 'keyboard', command: { mode: 'repeat', keys: ['K'], repeatCount: 3, repeatMs: 120 } } },
      { label: 'Wiper', material: 'toggle', icon: 'wiper', bodyColor: '#0f766e', borderColor: '#5eead4', textColor: '#ccfbf1', action: { kind: 'keyboard', command: { mode: 'press', keys: ['W'] } } },
      { label: 'Rain Lt', material: 'toggle', icon: 'rain', bodyColor: '#075985', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['R'] } } },
      { label: 'Marshal', material: 'backlit', icon: 'flag', bodyColor: '#064e3b', borderColor: '#34d399', textColor: '#d1fae5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Y'] } } },
      { label: 'GoodRace', material: 'backlit', icon: 'good-race', bodyColor: '#065f46', borderColor: '#6ee7b7', textColor: '#d1fae5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['G'] } } },
      { label: 'Horn', material: 'backlit', icon: 'horn', bodyColor: '#365314', borderColor: '#bef264', textColor: '#ecfccb', action: { kind: 'keyboard', command: { mode: 'press', keys: ['B'] } } },
      { label: 'Cam Next', material: 'glass', icon: 'camera-next', bodyColor: '#1f2937', borderColor: '#86efac', textColor: '#f0fdf4', action: { kind: 'iracing', command: { group: 'camera', name: 'camera:next' } } },
      { label: 'Cam Prev', material: 'glass', icon: 'camera-prev', bodyColor: '#1f2937', borderColor: '#86efac', textColor: '#f0fdf4', action: { kind: 'iracing', command: { group: 'camera', name: 'camera:previous' } } },
      { label: 'Overlay', material: 'glass', icon: 'overlay', bodyColor: '#4338ca', borderColor: '#a5b4fc', textColor: '#eef2ff', action: { kind: 'app', command: { name: 'overlays:toggle', overlayId: 'endurance-comms' } } },
      { label: 'Dash +', material: 'backlit', icon: 'dash-next', bodyColor: '#1e40af', borderColor: '#60a5fa', textColor: '#dbeafe', action: { kind: 'app', command: { name: 'dash:cycleNext' } } }
    ]
  }),
  createButtonBoxPanel({
    id: 'tp-a-endurance-night',
    name: 'Endurance — Noite',
    columns: 5,
    rows: 3,
    gap: 12,
    background: '#05070d',
    buttons: [
      { label: 'PTT', material: 'rotary', icon: 'mic', bodyColor: '#14532d', borderColor: '#4ade80', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'hold', keys: ['T'] } } },
      { label: 'Lights', material: 'toggle', icon: 'headlight', bodyColor: '#713f12', borderColor: '#fde047', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['H'] } } },
      { label: 'High', material: 'toggle', icon: 'highbeam', bodyColor: '#854d0e', borderColor: '#facc15', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['K'] } } },
      { label: 'Flash', material: 'backlit', icon: 'highbeam', bodyColor: '#a16207', borderColor: '#fef08a', textColor: '#fefce8', action: { kind: 'keyboard', command: { mode: 'repeat', keys: ['K'], repeatCount: 3, repeatMs: 120 } } },
      { label: 'Rain Lt', material: 'toggle', icon: 'rain', bodyColor: '#075985', borderColor: '#38bdf8', textColor: '#e0f2fe', action: { kind: 'keyboard', command: { mode: 'press', keys: ['R'] } } },
      { label: 'Wiper', material: 'toggle', icon: 'wiper', bodyColor: '#0f766e', borderColor: '#5eead4', textColor: '#ccfbf1', action: { kind: 'keyboard', command: { mode: 'press', keys: ['W'] } } },
      { label: 'Mute', material: 'toggle', icon: 'mute', bodyColor: '#365314', borderColor: '#84cc16', textColor: '#ecfccb', action: { kind: 'keyboard', command: { mode: 'toggle', keys: ['N'] } } },
      { label: 'Vol +', material: 'rotary', icon: 'volume-up', bodyColor: '#166534', borderColor: '#86efac', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['VolumeUp'] } } },
      { label: 'Vol -', material: 'rotary', icon: 'volume-down', bodyColor: '#166534', borderColor: '#86efac', textColor: '#dcfce7', action: { kind: 'keyboard', command: { mode: 'press', keys: ['VolumeDown'] } } },
      { label: 'Pass L', material: 'backlit', icon: 'pass-left', bodyColor: '#064e3b', borderColor: '#34d399', textColor: '#d1fae5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Left'] } } },
      { label: 'Pass R', material: 'backlit', icon: 'pass-right', bodyColor: '#064e3b', borderColor: '#34d399', textColor: '#d1fae5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Right'] } } },
      { label: 'Yellow', material: 'led_status', icon: 'yellow-flag', bodyColor: '#713f12', borderColor: '#facc15', textColor: '#fef9c3', action: { kind: 'keyboard', command: { mode: 'press', keys: ['Y'] } } },
      { label: 'GoodRace', material: 'backlit', icon: 'good-race', bodyColor: '#065f46', borderColor: '#6ee7b7', textColor: '#d1fae5', action: { kind: 'keyboard', command: { mode: 'press', keys: ['G'] } } },
      { label: 'Cam Next', material: 'glass', icon: 'camera-next', bodyColor: '#1f2937', borderColor: '#86efac', textColor: '#f0fdf4', action: { kind: 'iracing', command: { group: 'camera', name: 'camera:next' } } },
      { label: 'Overlay', material: 'glass', icon: 'overlay', bodyColor: '#4338ca', borderColor: '#a5b4fc', textColor: '#eef2ff', action: { kind: 'app', command: { name: 'overlays:toggle', overlayId: 'night-stint' } } }
    ]
  })
]
