import { createButtonBoxPanel, type ButtonBoxPanel } from "./touch-panel";

const none = { kind: "none" } as const;
const key = (
  keys: string[],
  mode: "press" | "chord" | "sequence" | "hold" | "toggle" | "repeat" = "press",
) => ({ kind: "keyboard", command: { mode, keys } }) as const;
const app = (overlayId: string) =>
  ({ kind: "app", command: { name: "overlays:toggle", overlayId } }) as const;

export const TOUCH_PRESETS_C: ButtonBoxPanel[] = [
  createButtonBoxPanel({
    id: "tp-c-pit-stop-hifi",
    name: "1. PIT STOP",
    columns: 3,
    rows: 2,
    gap: 14,
    background: "#050505",
    buttons: [
      {
        label: "PIT REQ",
        material: "guarded",
        icon: "pit-sign",
        bodyColor: "#4f1010",
        borderColor: "#ff4545",
        textColor: "#fff7f7",
        fontSize: 28,
        borderWidth: 3,
        action: key(["P"]),
      },
      {
        label: "FUEL",
        material: "backlit",
        icon: "fuel",
        bodyColor: "#4a2a05",
        borderColor: "#ffd24a",
        textColor: "#fff6d6",
        fontSize: 28,
        borderWidth: 3,
        action: {
          kind: "iracing",
          command: { group: "pit", name: "pit:addFuel", fuelLiters: 50 },
        },
      },
      {
        label: "TYRES",
        material: "backlit",
        icon: "tyre",
        bodyColor: "#073546",
        borderColor: "#49e7ff",
        textColor: "#e7fbff",
        fontSize: 28,
        borderWidth: 3,
        action: {
          kind: "iracing",
          command: { group: "pit", name: "pit:toggleTyreLf" },
        },
      },
      {
        label: "FLASH",
        material: "backlit",
        icon: "highbeam",
        bodyColor: "#063f4a",
        borderColor: "#59efff",
        textColor: "#e9fcff",
        fontSize: 25,
        borderWidth: 3,
        action: key(["F"]),
      },
      {
        label: "",
        material: "carbon",
        bodyColor: "#080b10",
        borderColor: "#1f2937",
        textColor: "#111827",
        borderWidth: 1,
        action: none,
      },
      {
        label: "LIMITER",
        material: "toggle",
        icon: "limiter",
        bodyColor: "#5f1212",
        borderColor: "#ff4d4d",
        textColor: "#fff1f1",
        fontSize: 25,
        borderWidth: 3,
        action: key(["L"]),
      },
    ],
  }),
  createButtonBoxPanel({
    id: "tp-c-cockpit-controls-hifi",
    name: "2. COCKPIT CONTROLS",
    columns: 3,
    rows: 4,
    gap: 10,
    background: "#050505",
    buttons: [
      {
        label: "-\nTC",
        material: "backlit",
        icon: "dash-prev",
        bodyColor: "#082f3b",
        borderColor: "#38e6ff",
        textColor: "#e6fbff",
        fontSize: 25,
        action: key(["PageDown"]),
      },
      {
        label: "TRAC CTRL",
        material: "rotary",
        icon: "settings",
        bodyColor: "#101418",
        borderColor: "#38e6ff",
        textColor: "#f5f7fa",
        fontSize: 22,
        action: app("tc-control"),
      },
      {
        label: "+\nTC",
        material: "backlit",
        icon: "dash-next",
        bodyColor: "#082f3b",
        borderColor: "#38e6ff",
        textColor: "#e6fbff",
        fontSize: 25,
        action: key(["PageUp"]),
      },
      {
        label: "-\nABS",
        material: "backlit",
        icon: "dash-prev",
        bodyColor: "#10223a",
        borderColor: "#5db7ff",
        textColor: "#edf7ff",
        fontSize: 25,
        action: key(["Shift", "PageDown"]),
      },
      {
        label: "ABS",
        material: "rotary",
        icon: "brake-bias",
        bodyColor: "#101418",
        borderColor: "#5db7ff",
        textColor: "#f5f7fa",
        fontSize: 22,
        action: app("abs-control"),
      },
      {
        label: "+\nABS",
        material: "backlit",
        icon: "dash-next",
        bodyColor: "#10223a",
        borderColor: "#5db7ff",
        textColor: "#edf7ff",
        fontSize: 25,
        action: key(["Shift", "PageUp"]),
      },
      {
        label: "-\nMAP",
        material: "backlit",
        icon: "dash-prev",
        bodyColor: "#3c3007",
        borderColor: "#ffd34e",
        textColor: "#fff7d6",
        fontSize: 25,
        action: key(["7"]),
      },
      {
        label: "ENG MAP",
        material: "rotary",
        icon: "map",
        bodyColor: "#14110a",
        borderColor: "#ffd34e",
        textColor: "#fff7d6",
        fontSize: 22,
        action: key(["8"]),
      },
      {
        label: "+\nMAP",
        material: "backlit",
        icon: "dash-next",
        bodyColor: "#3c3007",
        borderColor: "#ffd34e",
        textColor: "#fff7d6",
        fontSize: 25,
        action: key(["9"]),
      },
      {
        label: "-\nBIAS",
        material: "backlit",
        icon: "dash-prev",
        bodyColor: "#461010",
        borderColor: "#ff5555",
        textColor: "#fff1f1",
        fontSize: 25,
        action: key(["["]),
      },
      {
        label: "BRK BIAS",
        material: "rotary",
        icon: "brake-bias",
        bodyColor: "#180d0d",
        borderColor: "#ff5555",
        textColor: "#fff1f1",
        fontSize: 22,
        action: key(["B"]),
      },
      {
        label: "+\nBIAS",
        material: "backlit",
        icon: "dash-next",
        bodyColor: "#461010",
        borderColor: "#ff5555",
        textColor: "#fff1f1",
        fontSize: 25,
        action: key(["]"]),
      },
    ],
  }),
  createButtonBoxPanel({
    id: "tp-c-strategy-hifi",
    name: "3. STRATEGY",
    columns: 2,
    rows: 2,
    gap: 14,
    background: "#050505",
    buttons: [
      {
        label: "FUEL TARGET",
        material: "selector",
        icon: "fuel",
        bodyColor: "#3d2505",
        borderColor: "#ffbf35",
        textColor: "#fff4d6",
        fontSize: 25,
        borderWidth: 3,
        action: {
          kind: "iracing",
          command: { group: "pit", name: "pit:addFuel", fuelLiters: 50 },
        },
      },
      {
        label: "TYRE SET",
        material: "selector",
        icon: "tyre",
        bodyColor: "#063844",
        borderColor: "#40e7ff",
        textColor: "#e8fcff",
        fontSize: 25,
        borderWidth: 3,
        action: key(["Alt", "T", "3"], "sequence"),
      },
      {
        label: "DELTA MODE",
        material: "selector",
        icon: "delta",
        bodyColor: "#063942",
        borderColor: "#49efff",
        textColor: "#e8fcff",
        fontSize: 25,
        borderWidth: 3,
        action: app("relative-delta"),
      },
      {
        label: "SAVE LAP",
        material: "guarded",
        icon: "mark",
        bodyColor: "#4a1111",
        borderColor: "#ff5555",
        textColor: "#fff1f1",
        fontSize: 28,
        borderWidth: 3,
        action: key(["M"]),
      },
    ],
  }),
  createButtonBoxPanel({
    id: "tp-c-comms-radio-hifi",
    name: "4. COMMS / RADIO",
    columns: 2,
    rows: 3,
    gap: 12,
    background: "#050505",
    buttons: [
      {
        label: "PUSH TO TALK",
        material: "guarded",
        icon: "mic",
        bodyColor: "#4d1010",
        borderColor: "#ff5555",
        textColor: "#fff4f4",
        fontSize: 30,
        borderWidth: 3,
        action: key(["V"], "hold"),
      },
      {
        label: "RADIO CH 3",
        material: "selector",
        icon: "radio",
        bodyColor: "#101418",
        borderColor: "#6b7280",
        textColor: "#f8fafc",
        fontSize: 24,
        action: key(["3"]),
      },
      {
        label: "VOLUME",
        material: "rotary",
        icon: "volume-up",
        bodyColor: "#111827",
        borderColor: "#49eaff",
        textColor: "#f8fafc",
        fontSize: 24,
        action: key(["VolumeUp"]),
      },
      {
        label: "MARSHAL",
        material: "toggle",
        icon: "flag",
        bodyColor: "#064e55",
        borderColor: "#45e9ff",
        textColor: "#e8fcff",
        fontSize: 23,
        action: key(["Y"], "toggle"),
      },
      {
        label: "SPOTTER",
        material: "toggle",
        icon: "mic",
        bodyColor: "#064e55",
        borderColor: "#45e9ff",
        textColor: "#e8fcff",
        fontSize: 23,
        action: key(["S"], "toggle"),
      },
      {
        label: "MUTE",
        material: "backlit",
        icon: "mic-mute",
        bodyColor: "#1f2937",
        borderColor: "#94a3b8",
        textColor: "#f8fafc",
        fontSize: 23,
        action: key(["M"]),
      },
    ],
  }),
  createButtonBoxPanel({
    id: "tp-c-wheel-buttons-hifi",
    name: "5. WHEEL BUTTONS",
    columns: 3,
    rows: 3,
    gap: 12,
    background: "#050505",
    buttons: [
      {
        label: "DRINK",
        material: "rgb",
        icon: "wet",
        bodyColor: "#111827",
        borderColor: "#ffd22e",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["D"]),
      },
      {
        label: "DISPLAY",
        material: "rgb",
        icon: "dash",
        bodyColor: "#111827",
        borderColor: "#43eaff",
        textColor: "#f8fafc",
        fontSize: 19,
        action: { kind: "app", command: { name: "dash:cycleNext" } },
      },
      {
        label: "RADIO",
        material: "rgb",
        icon: "radio",
        bodyColor: "#111827",
        borderColor: "#ff4545",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["V"], "hold"),
      },
      {
        label: "LEFT",
        material: "rgb",
        icon: "arrow-left",
        bodyColor: "#111827",
        borderColor: "#43eaff",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["ArrowLeft"]),
      },
      {
        label: "MODE 0-6",
        material: "selector",
        icon: "settings",
        bodyColor: "#0d1117",
        borderColor: "#d1d5db",
        textColor: "#f9fafb",
        fontSize: 20,
        borderWidth: 3,
        action: key(["0"]),
      },
      {
        label: "RIGHT",
        material: "rgb",
        icon: "arrow-right",
        bodyColor: "#111827",
        borderColor: "#43eaff",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["ArrowRight"]),
      },
      {
        label: "WIPER",
        material: "rgb",
        icon: "wiper",
        bodyColor: "#111827",
        borderColor: "#43eaff",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["W"]),
      },
      {
        label: "MARKER",
        material: "rgb",
        icon: "mark",
        bodyColor: "#111827",
        borderColor: "#49e66a",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["M"]),
      },
      {
        label: "FLASH",
        material: "rgb",
        icon: "flash",
        bodyColor: "#111827",
        borderColor: "#ffd22e",
        textColor: "#f8fafc",
        fontSize: 19,
        action: key(["F"]),
      },
    ],
  }),
  createButtonBoxPanel({
    id: "tp-c-endurance-hifi",
    name: "6. ENDURANCE",
    columns: 3,
    rows: 2,
    gap: 14,
    background: "#050505",
    buttons: [
      {
        label: "DRIVER SWAP",
        material: "backlit",
        icon: "driver-swap",
        bodyColor: "#063842",
        borderColor: "#49eaff",
        textColor: "#e8fcff",
        fontSize: 24,
        borderWidth: 3,
        action: key(["Alt", "D"], "chord"),
      },
      {
        label: "LIGHTS",
        material: "toggle",
        icon: "headlight",
        bodyColor: "#063842",
        borderColor: "#49eaff",
        textColor: "#e8fcff",
        fontSize: 24,
        borderWidth: 3,
        action: key(["L"]),
      },
      {
        label: "WIPER SPD",
        material: "selector",
        icon: "wiper",
        bodyColor: "#063842",
        borderColor: "#49eaff",
        textColor: "#e8fcff",
        fontSize: 24,
        borderWidth: 3,
        action: key(["W"]),
      },
      {
        label: "BRAKE MAGIC",
        material: "selector",
        icon: "brake-bias",
        bodyColor: "#3c3007",
        borderColor: "#ffd34e",
        textColor: "#fff7d6",
        fontSize: 24,
        borderWidth: 3,
        action: key(["5"]),
      },
      {
        label: "NIGHT MODE",
        material: "toggle",
        icon: "moon",
        bodyColor: "#4a1111",
        borderColor: "#ff5555",
        textColor: "#fff1f1",
        fontSize: 24,
        borderWidth: 3,
        action: app("night-stint"),
      },
      {
        label: "SAVE LAP",
        material: "backlit",
        icon: "mark",
        bodyColor: "#1f2937",
        borderColor: "#94a3b8",
        textColor: "#f8fafc",
        fontSize: 24,
        action: key(["M"]),
      },
    ],
  }),
];

