// Pure Arduino sketch code-generation for the Pinout Designer.
//
// This module is intentionally free of Electron/Node side-effect imports so the
// generated firmware can be unit-compiled by a standalone harness (arduino-cli)
// without booting the app. `pinout-firmware.ts` re-exports `generateIno` from
// here and owns the IPC/compile/flash plumbing.

import type { BoardCatalogEntry, PinDirection, PinoutComponentDefinition } from '../../shared/board-catalog'
import { buildPinoutConfigPayload, type PinoutConfigPayload, type PinoutDesign } from '../../shared/pinout'

export function cSafe(value: string): string {
  // Strip characters that would break a C string literal / comment line, and
  // neutralize the block-comment delimiters (the mux map is emitted inside a
  // /* ... */ block, so a label containing */ must not terminate it).
  return String(value)
    .replace(/[\r\n]/g, ' ')
    .replace(/[^\x20-\x7E]/g, '')
    .replace(/["\\]/g, '')
    .replace(/\*\//g, '* /')
    .replace(/\/\*/g, '/ *')
}

export function generateIno(design: PinoutDesign, board: BoardCatalogEntry, library?: PinoutComponentDefinition[]): string {
  const config = buildPinoutConfigPayload(design, library)
  const directPins = config.pins.map((pin) => `  { "${cSafe(pin.componentId)}", "${cSafe(pin.role)}", ${arduinoPin(pin.pin)}, ${directionEnum(pin.direction)} }`).join(',\n') || '  { "", "", -1, PIN_INPUT_PULLUP }'
  const muxLines = config.muxes.map((mux) => {
    const channels = mux.channels.map((channel) => `{${channel.channel}, "${cSafe(channel.componentId)}", "${cSafe(channel.role)}"}`).join(', ')
    return `  // ${cSafe(mux.label)}\n  // SIG=${cSafe(mux.sigPin)} (${mux.sigMode}), S0..S3=${mux.selectPins.map(cSafe).join(', ')}, EN=${cSafe(mux.enPin) || 'unused'}\n  // Channels: ${channels || 'none'}`
  }).join('\n')
  const muxSetup = buildMuxPinSetup(config.muxes)

  // Which optional subsystems does this design actually use? Only emit the
  // matching code/includes so the sketch stays small and always compiles.
  const hasI2c = config.pins.some((pin) => pin.direction === 'i2c')
  const scanMuxes = config.muxes
    .map((mux) => ({ mux, select: mux.selectPins.map(arduinoPin), sig: arduinoPin(mux.sigPin), en: arduinoPin(mux.enPin) }))
    .filter((entry) => entry.sig !== '-1' && entry.select.every((pin) => pin !== '-1'))

  const i2cInclude = hasI2c ? '\n#include <Wire.h>' : ''
  const muxGlobals = scanMuxes.length > 0
    ? '\n' + scanMuxes.map((_, index) => `int muxLast${index}[16];`).join('\n') + '\n'
    : ''
  const muxEnable = scanMuxes
    .filter((entry) => entry.en !== '-1')
    .map((entry) => `  digitalWrite(${entry.en}, LOW); // ${cSafe(entry.mux.label)} EN active (enable mux)`)
    .join('\n')
  const muxInit = scanMuxes.length > 0
    ? scanMuxes.map((_, index) => `\n  for (uint8_t c = 0; c < 16; c++) muxLast${index}[c] = -1;`).join('')
    : ''
  const muxScanBody = scanMuxes.map((entry, index) => {
    const [s0, s1, s2, s3] = entry.select
    const read = entry.mux.sigMode === 'analog' ? `analogRead(${entry.sig})` : `digitalRead(${entry.sig})`
    const changed = entry.mux.sigMode === 'analog'
      ? `muxLast${index}[ch] < 0 || abs(v - muxLast${index}[ch]) > ANALOG_CHANGE_THRESHOLD`
      : `v != muxLast${index}[ch]`
    return `  for (uint8_t ch = 0; ch < 16; ch++) {\n` +
      `    digitalWrite(${s0}, (ch >> 0) & 1);\n` +
      `    digitalWrite(${s1}, (ch >> 1) & 1);\n` +
      `    digitalWrite(${s2}, (ch >> 2) & 1);\n` +
      `    digitalWrite(${s3}, (ch >> 3) & 1);\n` +
      `    delayMicroseconds(5);\n` +
      `    int v = ${read};\n` +
      `    if (${changed}) { muxLast${index}[ch] = v; Serial.print(F("MUX:${cSafe(entry.mux.label)}:C")); Serial.print(ch); Serial.print('='); Serial.println(v); }\n` +
      `  }`
  }).join('\n')

  // Embed the config as a double-JSON-encoded C string literal: JSON.stringify of
  // the JSON text yields a properly-escaped double-quoted literal (no raw-string
  // delimiter collision / injection from free-text labels).
  const lines: string[] = [
    `// Generated by Ultimate Sim App Pinout Designer.`,
    `// Board: ${board.name} (${design.boardId})`,
    `//`,
    `// ⚠️  WARNING — SERIAL DIAGNOSTIC / BENCH REPORTER ONLY.`,
    `// This generated sketch reports pin changes over Serial for bench testing.`,
    `// It does NOT include Joystick.h and does NOT expose HID button events.`,
    `// For a working HID button box, flash/use the companion-controls firmware.`,
    `//`,
    `// Bench-ready firmware: sets safe pin modes, reports input changes over`,
    `// serial (IN:/MUX:), and carries the pinout config. Add device libraries`,
    `// (FastLED, U8g2, Servo, ...) for full output behavior — those live in the`,
    `// matching companion firmware.`,
    ``,
    `#include <Arduino.h>${i2cInclude}`,
    ``,
    `enum PinDirection { PIN_INPUT_PULLUP, PIN_OUTPUT, PIN_ANALOG_INPUT, PIN_I2C_BUS };`,
    `struct DirectPin { const char* component; const char* role; int pin; PinDirection direction; };`,
    `DirectPin directPins[] = {`,
    directPins,
    `};`,
    `const unsigned int DIRECT_PIN_COUNT = sizeof(directPins) / sizeof(directPins[0]);`,
    `const int ANALOG_CHANGE_THRESHOLD = ${analogChangeThreshold(board)};`,
    `int lastValue[sizeof(directPins) / sizeof(directPins[0])];`,
    muxGlobals,
    `const char CONFIG_JSON[] PROGMEM = ${JSON.stringify(JSON.stringify(config))};`,
    ``,
    `void applyConfiguredPins() {`,
    `  // Give each pin the pinMode that matches its job so a beginner reading this`,
    `  // sketch can tell inputs from outputs at a glance.`,
    `  for (unsigned int i = 0; i < DIRECT_PIN_COUNT; i++) {`,
    `    if (directPins[i].pin < 0) continue;`,
    `    switch (directPins[i].direction) {`,
    `      case PIN_OUTPUT:`,
    `        // LED, WS2812 DIN, buzzer, servo signal, shift-register data/clock/latch.`,
    `        pinMode(directPins[i].pin, OUTPUT);`,
    `        break;`,
    `      case PIN_INPUT_PULLUP:`,
    `        // Push button, toggle switch, rotary-encoder pins wired to GND.`,
    `        pinMode(directPins[i].pin, INPUT_PULLUP);`,
    `        break;`,
    `      case PIN_ANALOG_INPUT:`,
    `        // Potentiometer wiper / analog sensor: analogRead() needs no pinMode().`,
    `        break;`,
    `      case PIN_I2C_BUS:`,
    `        // SDA/SCL belong to the I2C peripheral; Wire.begin() configures them.`,
    `        break;`,
    `    }`,
    `  }${muxSetup}`,
    `}`,
    ``,
    `void reportPin(const DirectPin &dp, int value) {`,
    `  Serial.print(F("IN:"));`,
    `  Serial.print(dp.component);`,
    `  Serial.print('/');`,
    `  Serial.print(dp.role);`,
    `  Serial.print('=');`,
    `  Serial.println(value);`,
    `}`,
    ``,
    `void scanInputs() {`,
    `  // Lightweight polling so the box reports inputs without any external library.`,
    `  static unsigned long lastScan = 0;`,
    `  unsigned long now = millis();`,
    `  if (now - lastScan < 5) return;`,
    `  lastScan = now;`,
    `  for (unsigned int i = 0; i < DIRECT_PIN_COUNT; i++) {`,
    `    if (directPins[i].pin < 0) continue;`,
    `    if (directPins[i].direction == PIN_INPUT_PULLUP) {`,
    `      int v = digitalRead(directPins[i].pin);`,
    `      if (v != lastValue[i]) { lastValue[i] = v; reportPin(directPins[i], v); }`,
    `    } else if (directPins[i].direction == PIN_ANALOG_INPUT) {`,
    `      int v = analogRead(directPins[i].pin);`,
    `      if (lastValue[i] < 0 || abs(v - lastValue[i]) > ANALOG_CHANGE_THRESHOLD) { lastValue[i] = v; reportPin(directPins[i], v); }`,
    `    }`,
    `  }`,
    scanMuxes.length > 0 ? muxScanBody : ``,
    `}`,
    ``,
    `void printConfig() {`,
    `  Serial.print(F("PCFG:ACTIVE:"));`,
    `  Serial.println(reinterpret_cast<const __FlashStringHelper *>(CONFIG_JSON));`,
    `}`,
    ``,
    `void setup() {`,
    `  Serial.begin(115200);`,
    `  applyConfiguredPins();`,
    `  for (unsigned int i = 0; i < DIRECT_PIN_COUNT; i++) lastValue[i] = -1;${hasI2c ? '\n  Wire.begin();' : ''}${muxEnable ? '\n' + muxEnable : ''}${muxInit}`,
    `}`,
    ``,
    `void loop() {`,
    `  if (Serial.available()) {`,
    `    String line = Serial.readStringUntil('\\n');`,
    `    line.trim();`,
    `    if (line == "?") {`,
    `      Serial.println(F("K:pinout=${cSafe(design.name)}"));`,
    `      Serial.println(F("KEND"));`,
    `    } else if (line.startsWith("PCFG:")) {`,
    `      // Generic configurable firmware command. This generated sketch embeds the`,
    `      // current config; a fully generic companion should parse the JSON after PCFG:`,
    `      // and persist it to EEPROM/LittleFS before replying PCFG:OK.`,
    `      Serial.println(F("PCFG:OK"));`,
    `    } else if (line == "PCFG?") {`,
    `      printConfig();`,
    `    }`,
    `  }`,
    `  scanInputs();`,
    `}`,
    ``,
    `/* Multiplexer map`,
    muxLines || '  none',
    `*/`,
    ``
  ]
  return lines.join('\n')
}

export function arduinoPin(pin: string): string {
  if (/^D\d+$/.test(pin)) return pin.slice(1)
  if (/^A\d+$/.test(pin)) return pin
  if (/^GPIO\d+$/.test(pin)) return pin.replace('GPIO', '')
  return '-1'
}

function directionEnum(direction: PinDirection): string {
  switch (direction) {
    case 'output':
      return 'PIN_OUTPUT'
    case 'analog':
      return 'PIN_ANALOG_INPUT'
    case 'i2c':
      return 'PIN_I2C_BUS'
    case 'input':
      return 'PIN_INPUT_PULLUP'
    default:
      return 'PIN_INPUT_PULLUP'
  }
}

function analogChangeThreshold(board: BoardCatalogEntry): number {
  const adcBits = board.mcu === 'ESP32' || board.mcu === 'ESP32-S3' ? 12 : 10
  return 8 * 2 ** Math.max(0, adcBits - 10)
}

function buildMuxPinSetup(muxes: PinoutConfigPayload['muxes']): string {
  const lines: string[] = []
  const selectLabels = ['S0', 'S1', 'S2', 'S3']
  for (const mux of muxes) {
    const label = cSafe(mux.label)
    mux.selectPins.forEach((selectPin, index) => {
      const num = arduinoPin(selectPin)
      if (num === '-1') return
      lines.push(`  pinMode(${num}, OUTPUT); // ${label} ${selectLabels[index]} select line`)
    })
    const enNum = arduinoPin(mux.enPin)
    if (enNum !== '-1') lines.push(`  pinMode(${enNum}, OUTPUT); // ${label} EN enable`)
    const sigNum = arduinoPin(mux.sigPin)
    if (sigNum !== '-1') {
      if (mux.sigMode === 'digital') lines.push(`  pinMode(${sigNum}, INPUT_PULLUP); // ${label} SIG common (digital read)`)
      else lines.push(`  // ${label} SIG=${cSafe(mux.sigPin)} is analog: analogRead() needs no pinMode().`)
    }
  }
  if (lines.length === 0) return ''
  return `\n\n  // CD74HC4067 multiplexer board pins: select lines (S0..S3) and EN are driven\n  // outputs; SIG is a pulled-up input for digital reads, or left alone for analog.\n${lines.join('\n')}`
}
